//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppHotelManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HotelDBEntities : DbContext
    {
        public HotelDBEntities()
            : base("name=HotelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingStatu> BookingStatus { get; set; }
        public virtual DbSet<CustomerService> CustomerServices { get; set; }
        public virtual DbSet<Invoid> Invoids { get; set; }
        public virtual DbSet<MonthlyR> MonthlyRs { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<RoomBooking> RoomBookings { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<ServiceServed> ServiceServeds { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int sp_changeActive_InvoidAndRooom(Nullable<int> invID)
        {
            var invIDParameter = invID.HasValue ?
                new ObjectParameter("InvID", invID) :
                new ObjectParameter("InvID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_changeActive_InvoidAndRooom", invIDParameter);
        }
    
        public virtual int Sp_get_list_roomBooking_id()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_get_list_roomBooking_id");
        }
    
        public virtual int sp_Invoice_ListAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Invoice_ListAll");
        }
    
        public virtual int sp_Invoice_ListAll_0()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Invoice_ListAll_0");
        }
    
        public virtual int sp_Invoice_ListAll_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Invoice_ListAll_1");
        }
    
        public virtual ObjectResult<sp_service_ListAll_Result> sp_service_ListAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_service_ListAll_Result>("sp_service_ListAll");
        }
    }
}
